version: '3.3'
services:
  nginx-ssl-proxy:
    image: hakito/nginx-ssl-proxy
    environment:
      UPSTREAM: 127.0.0.1:8080
      SERVERNAME: test.example.com
      DO_AUTH: required
      PROXY_PASSWORD: secure
    ports:
      - 443:443
      - 80:80
